#!/usr/bin/bash

set -o errexit

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

PKGSRC_VERSION='2015Q3'

# Munin plugins
MUNIN_PLUGIN_VERSION='0.7'
MUNIN_PLUGINS="
	cpu
	df
	iostat
	load
	uptime
	users
	vmstat
	io_busy_zfs
	io_bytes_zfs
	io_ops_zfs
	if_net0
	pkg_audit
"

echo "* Use the skylime pkgsrc mirror"
echo "http://pkgsrc.smartos.skylime.net/packages/SmartOS/${PKGSRC_VERSION}/x86_64/All" > /opt/local/etc/pkgin/repositories.conf
pkg_admin rebuild
pkgin -y up

## MUNIN
echo "* Create munin template file that will be used during mdata setup"
cp /opt/local/etc/munin/munin-node.conf /opt/local/etc/munin/munin-node.conf.tpl

echo "* Download and install community munin plugins (overwrite all other plugins)"
curl -L https://github.com/drscream/smartos-munin-plugins/archive/v${MUNIN_PLUGIN_VERSION}.tar.gz | gtar xz -C /opt/local/lib/munin/plugins --strip-components=1

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Create rsyslog.d folder for extra configuration files"
mkdir -p /opt/local/etc/rsyslog.d

echo "* Cleaning up."
rm -rf /root/*
sm-prepare-image -y
